<!--NAVIGATION-->

<a href="https://colab.research.google.com/github/bpesquet/machine-learning-katas/blob/master/classic-datasets/Iris.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open in Google Colaboratory"></a>

# Guided ML With The Iris Dataset

| Learning type | Activity type | Objective |
| - | - | - |
| Supervised | Multiclass classification | Identify a flower's class |

Contents:
1. Loading the data
2. Setting up supervised learning problem (selecting features)
3. Creating a first model
    - Creating train and test datasets
    - Normalizing train and test
    - Fitting and predicting
4. Evaluate the frist model predictions
5. Crossvalidation of the model
6. Creating an end to end ML pipeline
    - Train/Test Split
    - Normalize
    - Crossvalidations
    - Model
    - fitting and predicting

## Instructions with NBGrader removed

Complete the cells beginning with `# YOUR CODE HERE` and run the subsequent cells to check your code.

## About the dataset

[Iris](https://archive.ics.uci.edu/ml/datasets/iris) is a well-known multiclass dataset. It contains 3 classes of flowers with 50 examples each. There are a total of 4 features for each flower.

![](./classic-datasets/images/Iris-versicolor-21_1.jpg)

## Package setups

1. Run the following two cells to initalize the required libraries. 

In [1]:
#to debug package errors
import sys
sys.path
sys.executable

'/Users/ns/anaconda3/envs/bk_py3/bin/python'

In [2]:
# Import needed packages
# You may add or remove packages should you need them
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn import datasets
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.pipeline import make_pipeline

# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
# Set Seaborn aesthetic parameters to defaults
sns.set()

## Step 1: Loading the data

1. Load the iris dataset using ```datasets.load_iris()```
2. Investigate the data structure with ```.keys()```
3. Construct a dataframe from the dataset
4. Create a 'target' and a 'class' column that contains the target names and values
5. Display a random sample of the dataframe 

In [8]:
#Your code here.

#load the dataset
dataset = datasets.load_iris()
#display the 
dataset.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [9]:
# Put data in a pandas DataFrame
df_iris = pd.DataFrame(dataset.data, columns=dataset.feature_names)
# Add target and class to DataFrame
df_iris['target'] = dataset.target
df_iris['class'] = dataset.target_names[dataset.target]
#rename the columns - remove the (cm)
df_iris.columns = [col.replace('(cm)', '').strip() for col in df_iris.columns]
# Show 10 random samples
df_iris.sample(n=10)

sepal length  sepal width  petal length  petal width  target       class
69            5.6          2.5           3.9          1.1       1  versicolor
6             4.6          3.4           1.4          0.3       0      setosa
134           6.1          2.6           5.6          1.4       2   virginica
39            5.1          3.4           1.5          0.2       0      setosa
75            6.6          3.0           4.4          1.4       1  versicolor
103           6.3          2.9           5.6          1.8       2   virginica
142           5.8          2.7           5.1          1.9       2   virginica
0             5.1          3.5           1.4          0.2       0      setosa
104           6.5          3.0           5.8          2.2       2   virginica
72            6.3          2.5           4.9          1.5       1  versicolor

### Question
Find the X and y values we're looking for. Notice that y is categorical and thus, we could **one-hot encode it** if we are looking at **class** or we can just pick **target**. In order to one hot encode we have  to re-shape `y` it using the **.get_dummies** function. 

## For the purpose of this exercise, do not use hot encoding, go only for target but think about if you have to drop it somewhere or not...

In [10]:
# YOUR CODE HERE



## Step 2: Setting up supervised learning problem (selecting features)

Feature selection is an essential step in improving a model's perfromance. In the first version of the model we will use the 'sepal length' and 'sepal width' as predicting features. Later we will see the effect of adding additional features.

1. Assign the values of the 'target' to Y as a numpy array
2. Assign the remaining feature values to X as a numpy array
3. Check the shape of X and Y. Check the first few values.
    - Can we confirm our X and Y are created correctly?

In [11]:
#your code here
Y = df_iris['target'].values
print(Y.shape)
Y[:5]

(150,)


array([0, 0, 0, 0, 0])

In [12]:
#your code here
X = df_iris[['sepal length', 'sepal width']].values
print(X.shape)
X[:5]

(150, 2)


array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

## Step 3: Creating the first model

In lecture we learned about creating a train and test datasets, normalizing, and fitting a model. In this step we will see how to build a simple version of this.

We have to be careful when constructing our train and test datasets. First, when we create train and test datasets we have to be careful that we always have the same datapoints in each set. Otherwise our results won't be reproduceable or we might introduce a bias into our model.

We also need to be attentive to when we normalize the data. What would be the effect of normalizing the data (i.e. with StandardScaler to a range between 0 - 1) before we create our train and test sets? Effectively we would use information in the test set to structure the values in the training set and vice versa. Therefore normalizing train and test independently is the preferred method.

1. Create X_train, X_test, Y_train, Y_test using ```train_test_split()``` with an 80/20 train/test split. Look in the SKLearn documentation to understand how the function works.
    - Inspect the first few rows of X_train.
    - Run the cell a few times. Do the first few rows change?
    - What option can we use in ```train_test_split()``` to stop this from happening?
2. Normalize the train and test datasets with ```StandardScaler```
    - We can fit the transform with ```.fit()``` and ```.transform()``` to apply it. Look in the documentation for an esample of how to do this.
    - Does it make sense to normalize Y_train and Y_test?
3. Initalize a ```LogisticRegression()``` model and use the ```.fit()``` method to initalize the first model.
    - We will pass the X_train and Y_train variables to the ```.fit()``` method.
    - Once the model is fit, use the ```.predict()``` with the X_test and save the output as predictions.

In [13]:
#split train and test data 80/20
#your code here
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

X_train[:5]

array([[6.4, 3.1],
       [5.4, 3. ],
       [5.2, 3.5],
       [6.1, 3. ],
       [6.4, 2.8]])

In [14]:
#normalize the dataset
#your code here

#create and fit the scaler object on the training data
scaler = StandardScaler().fit(X_train)

#transform the train and test datasets
X_train = scaler.transform(X_train) 
X_test = scaler.transform(X_test)

X_train[:5]

array([[ 0.61303014,  0.10850105],
       [-0.56776627, -0.12400121],
       [-0.80392556,  1.03851009],
       [ 0.25879121, -0.12400121],
       [ 0.61303014, -0.58900572]])

In [15]:
#initalize and fit with Logistic Regression
#your code here

#initalize the logistic regressor
clf = LogisticRegression(solver='lbfgs', multi_class='multinomial').fit(X_train, Y_train)
#make predictions
predictions = clf.predict(X_test)
predictions


array([1, 1, 0, 2, 0, 2, 0, 2, 2, 1, 1, 2, 1, 2, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 2, 0, 0, 2, 1, 0])

## Step 4: Evaluate the frist model's predictions

We will learn more about how to evaluate the performance of a classifier in later lessons. For now we will use % accuracy as our metric. It is important to know that this metric only helps us understand the specific performance of our model and not, for example, where we can improve it, or where it already perfoms well.

1. Use ```.score()``` to evaluate the performance of our first model.

In [16]:
#evaluating the performace of our first model
#your code here

clf.score(X_test, Y_test)

0.7333333333333333

## Step 5: Crossvalidation of the model
Our first model achived ~90% accruacy. This is quite good. How do we know it is reproducable? If we run the model again and our performance is 85% which is correct? And what about improving our model? Can you think of one thing we can do to potentially improve the model?

#### Crossvalidation
Corssvalidation is when we create multiple X and Y datasets. On each dataset we train and fit the model. We then average the results and return a 'crossvalidated' accruacy.

1. Initalize a new version of the model you trained above with the same paramters.
2. Use ```cross_validate()``` to run the model with 5 crossvalidation folds. 

In [17]:
#model with cross validation
#your code here

clf_cv = LogisticRegression(solver='lbfgs', multi_class='multinomial').fit(X_train, Y_train)

#cross validate the training set
cv = cross_validate(clf_cv, X_train, Y_train, cv=5)

def print_scores(cv):
    #print out cross validation scores
    [print('Crossvalidation fold: {}  Accruacy: {}'.format(n, score)) for n, score in enumerate(cv['test_score'])]
    #print out the mean of the cross validation
    print('Mean train cross validation score {}'.format(cv['test_score'].mean()))
    
print_scores(cv)

Crossvalidation fold: 0  Accruacy: 0.92
Crossvalidation fold: 1  Accruacy: 0.68
Crossvalidation fold: 2  Accruacy: 0.8333333333333334
Crossvalidation fold: 3  Accruacy: 0.7916666666666666
Crossvalidation fold: 4  Accruacy: 0.8181818181818182
Mean train cross validation score 0.8086363636363636


## Step 6: Creating an end to end ML pipeline
Congraulations you've trained, crossvalidated, predicted, and evaluated your frist classifier. Now that you understand the basic steps we will look at a way to combine all these steps together.

Before we go further think about what you would have to do if you wanted to change the model. Intalize a new model, change the vairables, redo the cross validation...etc. Seems like a lot. And when we have to change lots of code it is easy to make mistakes. And what if you wanted to try many models and see which one performed best? Or try changing many different features? How could you do it without writing each one out as we have?

The solution is to use SKLearn's pipeline class. A pipeline is an object that will execute the various steps in the machine learning process. We can choose what elements we want in the pipeline and those that we do not. Once setup, we can rapidly change models, or input data and have it return our results in an ordered way.


1. Initalize a scaler and a classifer object like we did previously.
2. Use the ```make_pipeline()``` function to construct a transofmraiton pipeline for the scaler and the classifier
3. Input the pipeline object to the cross_validator and evaluate with 5 folds.
4. Print out your results (hint: make a function for repetitve tasks like printing)

In [25]:
#define the scaler
scaler = StandardScaler();
#define the classifier
classifier = LogisticRegression(solver='lbfgs', multi_class='multinomial');
#make the pipeline
pipe = make_pipeline(scaler, classifier);
#run the cross validation
scores = cross_validate(pipe, X, Y, cv=5);
#print results
print_scores(scores)

Crossvalidation fold: 0  Accruacy: 0.7333333333333333
Crossvalidation fold: 1  Accruacy: 0.8333333333333334
Crossvalidation fold: 2  Accruacy: 0.7666666666666667
Crossvalidation fold: 3  Accruacy: 0.8666666666666667
Crossvalidation fold: 4  Accruacy: 0.8666666666666667
Mean train cross validation score 0.8133333333333332


## Challenge Exercise

In this notebook we only used two features to predict the class of the flower. We also did not do any hypter parameter tuning. The challenge is to impove the prediction results. Some ideas we can try:
1. Add features to the input and run the cross validation pipeline
2. Investigate how to use ```GridSearchCV```, a powerful funtion that searches through hyperparmetrs and does cross validation.
    - Hint: Input the pipeline directly into GridSearchCV
3. Try a different models like RandomForest or SVM.

In [19]:
#your challenge code here
from sklearn.model_selection import GridSearchCV


In [32]:
params = {'logisticregression__penalty' : ['l2', 'none'],
         'logisticregression__C' : [0.1, 1, 10]}

In [33]:
gscv = GridSearchCV(pipe, params, cv=5, verbose=0)

In [39]:
gscv.fit(X_train, Y_train)
results = gscv.cv_results_;

/Users/ns/anaconda3/envs/bk_py3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:1510: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  "Setting penalty='none' will ignore the C and l1_ratio "
/Users/ns/anaconda3/envs/bk_py3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:1510: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  "Setting penalty='none' will ignore the C and l1_ratio "
/Users/ns/anaconda3/envs/bk_py3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:1510: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  "Setting penalty='none' will ignore the C and l1_ratio "
/Users/ns/anaconda3/envs/bk_py3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:1510: UserWarning: Setting penalty='none' will ignore the C and l1_ratio parameters
  "Setting penalty='none' will ignore the C and l1_ratio "
/Users/ns/anaconda3/envs/bk_py3/lib/python3.6/site-packa

In [40]:
results

{'mean_fit_time': array([0.00532427, 0.01363163, 0.0056736 , 0.0119647 , 0.00760627,
        0.01326752]),
 'std_fit_time': array([0.00062045, 0.00163466, 0.0002454 , 0.00166928, 0.00075183,
        0.0016193 ]),
 'mean_score_time': array([0.00051188, 0.00048175, 0.00039082, 0.00041046, 0.00047536,
        0.00046048]),
 'std_score_time': array([6.27857119e-05, 1.01849403e-04, 2.16651003e-05, 4.11136508e-05,
        8.21538532e-05, 4.45062035e-05]),
 'param_logisticregression__C': masked_array(data=[0.1, 0.1, 1, 1, 10, 10],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_logisticregression__penalty': masked_array(data=['l2', 'none', 'l2', 'none', 'l2', 'none'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'logisticregression__C': 0.1,
   'logisticregression__penalty': 'l2'},
  {'logisticregression__C': 0.1, 'logisticregression__pe