# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

#### Create an array of 10 ones

#### Create an array of 10 fives

#### Create an array of the integers from 10 to 50

#### Create an array of all the even integers from 10 to 50

#### Create a 3x3 matrix with values ranging from 0 to 8

#### Create a 3x3 identity matrix

#### Use NumPy to generate a random number between 0 and 1

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [2]:
mat = np.arange(1,26).reshape(5,5)

mat

In [1]:
mat[3][4]

NameError: name 'mat' is not defined

In [4]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL ABOVE
code = 'here'

In [5]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [6]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL ABOVE
code = 'here'

In [7]:
mat[-1]

array([21, 22, 23, 24, 25])

In [8]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL ABOVE
code = 'here'

In [9]:
mat[-2,-1]

20

In [10]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL ABOVE
code = 'here'

In [11]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [12]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL ABOVE
code = 'here'

### Now do the following

#### Get the sum of all the values in mat

#### Get the standard deviation of the values in mat

#### Get the sum of all the columns in mat

# Great Job!