In [1]:
#Dependencies
import numpy as np

In [2]:
#Input Data
input_data = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
output_labels = np.array([[0, 1, 1, 0]]).T

print(input_data)
print(output_labels)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [3]:
#Sigmoid Activation Function
def activate(x, deriv=False):
    if (deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [4]:
#weight matrix
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print(synaptic_weights)

[[0.685076  ]
 [0.79238219]
 [0.39258275]]


In [5]:
##output for a layer in the neural network example
print(activate(np.dot(input_data, synaptic_weights)))

[[0.59690429]
 [0.86646302]
 [0.74605067]
 [0.76583934]]


In [6]:
#training example
output = activate(np.dot(input_data, synaptic_weights))
error = output_labels - output

synaptic_weights += np.dot(input_data.T, error * activate(output, True)) #Gradient Descent

print(error)
print("")
print(input_data.T)
print("")
print(error * activate(output, True))

[[-0.59690429]
 [ 0.13353698]
 [ 0.25394933]
 [-0.76583934]]

[[0 1 1 0]
 [0 1 0 1]
 [1 1 1 1]]

[[-0.14362088]
 [ 0.01545088]
 [ 0.048113  ]
 [-0.13733754]]


In [7]:
#example of iteration of training
for iteration in range(10000):
    output = activate(np.dot(input_data, synaptic_weights))
    error = output_labels - output
    synaptic_weights += np.dot(input_data.T, error * activate(output, True))

In [8]:
#testing example
print(activate(np.dot(np.array([1, 0, 0]), synaptic_weights))) 
#Will be approximetly 1 which is close to the 1st element

[0.99993705]


In [9]:
#2 weight values, 1 for each output layer that is used as an input layer in the neural network
synaptic_weight_for_layer_0 = 2*np.random.random((3, 4)) - 1
synaptic_weight_for_layer_1 = 2*np.random.random((4, 1)) - 1

print(synaptic_weight_for_layer_0)
print(synaptic_weight_for_layer_1)

[[-0.91787093  0.32913042  0.34619714  0.56317092]
 [ 0.54616341 -0.28710954 -0.52598912 -0.7492062 ]
 [-0.02657361  0.47927773  0.69286338  0.07692263]]
[[-0.91336437]
 [-0.48032995]
 [-0.12863102]
 [-0.83384515]]


In [10]:
#Real Training!
for j in range(100000):
    
    #Forward Propagation through the network layers 0, 1, & 2
    network_layer_0 = input_data
    network_layer_1 = activate(np.dot(network_layer_0, synaptic_weight_for_layer_0))
    network_layer_2 = activate(np.dot(network_layer_1, synaptic_weight_for_layer_1))
    
    #calculate the error for network_layer_2
    network_layer_2_error = output_labels - network_layer_2
    
    if j % 10000 == 0:
        print("Error: " + str(np.mean(np.abs(network_layer_2_error))))
    
    #Use the network_layer_2_error to compute the gradient to start backpropagation
    layer_2_gradient = network_layer_2_error * activate(network_layer_2, deriv=True)
    
    #calculate the error for network_layer_1
    network_layer_1_error = layer_2_gradient.dot(synaptic_weight_for_layer_1.T)
    
    #Use the network_layer_1_error to compute the gradient for network_layer_1
    layer_1_gradient = network_layer_1_error * activate(network_layer_1, deriv=True)
    
    #Update the synaptic weights using the gradients
    synaptic_weight_for_layer_1 += network_layer_1.T.dot(layer_2_gradient)
    synaptic_weight_for_layer_0 += network_layer_0.T.dot(layer_1_gradient)

Error: 0.49638680210188
Error: 0.005168058398431066
Error: 0.0035556846457904653
Error: 0.002862988248869929
Error: 0.002456883001482278
Error: 0.002182846694493733
Error: 0.0019822557701191985
Error: 0.0018273914897096871
Error: 0.0017032414625170254
Error: 0.001600882068650963


In [11]:
# Real testing!
print(np.dot(np.array([0, 0, 1]), synaptic_weight_for_layer_0))

[ 2.56256663e+00 -6.20888037e-01 -1.47064095e+00  2.27319070e-03]
