In [1]:
#Dependencies
import numpy as np

In [2]:
#Input Data
input_data = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
output_labels = np.array([[0, 1, 1, 0]]).T

print(input_data)
print(output_labels)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [3]:
#Sigmoid Activation Function
def activate(x, deriv=False):
    if (deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [4]:
#weight matrix
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print(synaptic_weights)

[[-0.32189098]
 [-0.45614083]
 [-0.92735386]]


In [5]:
##output for a layer in the neural network example
print(activate(np.dot(input_data, synaptic_weights)))

[[0.28346187]
 [0.15376317]
 [0.22283089]
 [0.20044832]]


In [6]:
#training example
output = activate(np.dot(input_data, synaptic_weights))
error = output_labels - output

synaptic_weights += np.dot(input_data.T, error * activate(output, True)) #Gradient Descent

print(error)
print("")
print(input_data.T)
print("")
print(error * activate(output, True))

[[-0.28346187]
 [ 0.84623683]
 [ 0.77716911]
 [-0.20044832]]

[[0 1 1 0]
 [0 1 0 1]
 [1 1 1 1]]

[[-0.05757429]
 [ 0.11011239]
 [ 0.13458804]
 [-0.03212561]]


In [7]:
#example of iteration of training
for iteration in range(10000):
    output = activate(np.dot(input_data, synaptic_weights))
    error = output_labels - output
    synaptic_weights += np.dot(input_data.T, error * activate(output, True))

In [8]:
#testing example
print(activate(np.dot(np.array([1, 0, 0]), synaptic_weights))) 
#Will be approximetly 1 which is close to the 1st element

[0.99993704]


In [9]:
#2 weight values, 1 for each output layer that is used as an input layer in the neural network
synaptic_weight_for_layer_0 = 2*np.random.random((3, 4)) - 1
synaptic_weight_for_layer_1 = 2*np.random.random((4, 1)) - 1

print(synaptic_weight_for_layer_0)
print(synaptic_weight_for_layer_1)

[[-0.91220755  0.88497841 -0.51177945  0.75551023]
 [ 0.15480081 -0.88583977 -0.26611826  0.94485993]
 [ 0.02448992 -0.14575077 -0.24933606 -0.84971329]]
[[0.696956  ]
 [0.97778092]
 [0.64851122]
 [0.14675781]]


In [10]:
#Real Training!
for j in range(100000):
    
    #Forward Propagation through the network layers 0, 1, & 2
    network_layer_0 = input_data
    network_layer_1 = activate(np.dot(network_layer_0, synaptic_weight_for_layer_0))
    network_layer_2 = activate(np.dot(network_layer_1, synaptic_weight_for_layer_1))
    
    #calculate the error for network_layer_2
    network_layer_2_error = output_labels - network_layer_2
    
    if j % 10000 == 0:
        print("Error: " + str(np.mean(np.abs(network_layer_2_error))))
    
    #Use the network_layer_2_error to compute the gradient to start backpropagation
    layer_2_gradient = network_layer_2_error * activate(network_layer_2, deriv=True)
    
    #calculate the error for network_layer_1
    network_layer_1_error = layer_2_gradient.dot(synaptic_weight_for_layer_1.T)
    
    #Use the network_layer_1_error to compute the gradient for network_layer_1
    layer_1_gradient = network_layer_1_error * activate(network_layer_1, deriv=True)
    
    #Update the synaptic weights using the gradients
    synaptic_weight_for_layer_1 += network_layer_1.T.dot(layer_2_gradient)
    synaptic_weight_for_layer_0 += network_layer_0.T.dot(layer_1_gradient)

Error: 0.4998031089091461
Error: 0.00474680959569087
Error: 0.0032704695268786594
Error: 0.002634858640251428
Error: 0.0022618003272018737
Error: 0.002009878747162558
Error: 0.001825378162972107
Error: 0.0016828790876120129
Error: 0.0015686056348860758
Error: 0.0014743650240043684


In [11]:
# Real testing!
print(np.dot(np.array([0, 0, 1]), synaptic_weight_for_layer_0))

[ 1.85792063 -1.92986582  0.97842644 -1.08819976]
