In [2]:
#Dependencies
import numpy as np

In [3]:
#Input Data
input_data = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
output_labels = np.array([[0, 1, 1, 0]]).T

print(input_data)
print(output_labels)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [5]:
#Sigmoid Activation Function
def activate(x, deriv=False):
    if (deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [6]:
#weight matrix
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print(synaptic_weights)

[[ 0.5042468 ]
 [ 0.2783455 ]
 [ 0.06313148]]


In [7]:
##output for a layer in the neural network example
print(activate(np.dot(input_data, synaptic_weights)))

[[ 0.51577763]
 [ 0.69966934]
 [ 0.63815801]
 [ 0.58454925]]


In [8]:
#training example
output = activate(np.dot(input_data, synaptic_weights))
error = output_labels - output

synaptic_weights += np.dot(input_data.T, error * activate(output, True)) #Gradient Descent

print(error)
print("")
print(input_data.T)
print("")
print(error * activate(output, True))

[[-0.51577763]
 [ 0.30033066]
 [ 0.36184199]
 [-0.58454925]]

[[0 1 1 0]
 [0 1 0 1]
 [1 1 1 1]]

[[-0.12881601]
 [ 0.06310913]
 [ 0.08355379]
 [-0.14195862]]


In [7]:
#example of iteration of training
for iteration in range(10000):
    output = activate(np.dot(input_data, synaptic_weights))
    error = output_labels - output
    synaptic_weights += np.dot(input_data.T, error * activate(output, True))

In [8]:
#testing example
print(activate(np.dot(np.array([1, 0, 0]), synaptic_weights))) 
#Will be approximetly 1 which is close to the 1st element

[ 0.99993703]


In [10]:
#2 weight values, 1 for each output layer that is used as an input layer in the neural network
synaptic_weight_for_layer_0 = 2*np.random.random((3, 4)) - 1
synaptic_weight_for_layer_1 = 2*np.random.random((4, 1)) - 1

print(synaptic_weight_for_layer_0)
print(synaptic_weight_for_layer_1)

[[ 0.38056945 -0.44684551  0.10184672  0.37547474]
 [ 0.33190538 -0.36729165 -0.74922787 -0.87491056]
 [ 0.02232939 -0.71299319  0.39525954 -0.34915541]]
[[ 0.13006039]
 [ 0.80952107]
 [-0.49163424]
 [-0.82428326]]


In [18]:
#Real Training!
for j in range(100000):
    
    #Forward Propagation through the network layers 0, 1, & 2
    network_layer_0 = input_data
    network_layer_1 = activate(np.dot(network_layer_0, synaptic_weight_for_layer_0))
    network_layer_2 = activate(np.dot(network_layer_1, synaptic_weight_for_layer_1))
    
    #calculate the error for network_layer_2
    network_layer_2_error = output_labels - network_layer_2
    
    if j % 10000 == 0:
        print("Error: " + str(np.mean(np.abs(network_layer_2_error))))
    
    #Use the network_layer_2_error to compute the gradient to start backpropagation
    layer_2_gradient = network_layer_2_error * activate(network_layer_2, deriv=True)
    
    #calculate the error for network_layer_1
    network_layer_1_error = layer_2_gradient.dot(synaptic_weight_for_layer_1.T)
    
    #Use the network_layer_1_error to compute the gradient for network_layer_1
    layer_1_gradient = network_layer_1_error * activate(network_layer_1, deriv=True)
    
    #Update the synaptic weights using the gradients
    synaptic_weight_for_layer_1 += network_layer_1.T.dot(layer_2_gradient)
    synaptic_weight_for_layer_0 += network_layer_0.T.dot(layer_1_gradient)

Error: 0.0006394394083
Error: 0.000631321281999
Error: 0.000623499251598
Error: 0.000615955825948
Error: 0.000608674924047
Error: 0.000601641732335
Error: 0.000594842579242
Error: 0.000588264824569
Error: 0.000581896761687
Error: 0.00057572753082


In [20]:
# Real testing!
print(np.dot(np.array([0, 0, 1]), synaptic_weight_for_layer_0))

[-1.70279022 -1.29239968  1.91063566  1.53532246]
