In [1]:
import numpy as np #linear algebra

In [2]:
#Input Data
input_data = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
output_labels = np.array([[0, 1, 1, 0]]).T

In [3]:
print(input_data)
print(output_labels)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [4]:
def activate(x, deriv=False):
    if (deriv==True):
        return(x*(1-x))
    return 1/(1+np.exp(-x))

In [5]:
#weight matrix
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print(synaptic_weights)

[[-0.37680614]
 [-0.37488565]
 [ 0.4528899 ]]


In [6]:
output = activate(np.dot(input_data, synaptic_weights))

##This is our first guess
output

array([[ 0.61132611],
       [ 0.4258504 ],
       [ 0.51901177],
       [ 0.51949118]])

In [7]:
error = output_labels - output

In [8]:
#example of iteration of training
for iteration in range(10000):
    output = activate(np.dot(input_data, synaptic_weights))
    error = output_labels - output
    synaptic_weights += np.dot(input_data.T, error * activate(output, True))

In [9]:
#testing example
print(activate(np.dot(np.array([1, 0, 0]), synaptic_weights)))
#Will be approximetly 1 which is close to the 1st element

[ 0.99993702]


In [10]:
#2 weight values, 1 for each output layer that is used as an input layer in the neural network
synaptic_weight_for_layer_0 = 2*np.random.random((3, 4)) - 1
synaptic_weight_for_layer_1 = 2*np.random.random((4, 1)) - 1

In [11]:
print(synaptic_weight_for_layer_0)
print(synaptic_weight_for_layer_1)

[[-0.85420555  0.76311662  0.99509773  0.01521023]
 [ 0.24173397 -0.59290597 -0.0744871   0.25204814]
 [ 0.82398167  0.52115678 -0.39260628  0.80329656]]
[[ 0.42722431]
 [-0.03774017]
 [-0.6744803 ]
 [ 0.26635957]]


In [12]:
#Real Training!
for j in range(100000):
    
    #Forward Propagation through the network layers 0, 1, & 2
    network_layer_0 = input_data
    # 4, 3
    network_layer_1 = activate(np.dot(network_layer_0, synaptic_weight_for_layer_0))
    #4, 4                                #4,3               #3,4
    network_layer_2 = activate(np.dot(network_layer_1, synaptic_weight_for_layer_1))
    #4,1                                 #4,4               #4,1
    
    #calculate the error for network_layer_2
    network_layer_2_error = output_labels - network_layer_2
    #4,1                        #4,1            #4,1
    
    if j % 10000 == 0:
        print("Error: " + str(np.mean(np.abs(network_layer_2_error))))
        
    #Use the network_layer_2_error to compute the gradient to start backpropagation
    layer_2_gradient = network_layer_2_error * activate(network_layer_2, deriv=True)
    #4,1                    #4,1                  #4,1
    
    #calculate the error for network_layer_1
    network_layer_1_error = layer_2_gradient.dot(synaptic_weight_for_layer_1.T)
    #4,4                      #4,1                  #1,4
    
    #Use the network_layer_1_error to compute the gradient for network_layer_1
    layer_1_gradient = network_layer_1_error * activate(network_layer_1, deriv=True)
    #4,4                  #4,4                      #4,4
    
    #Update the synaptic weights using the gradients
    synaptic_weight_for_layer_1 += network_layer_1.T.dot(layer_2_gradient)
    #4,1                              #4,4                 #4,1
    synaptic_weight_for_layer_0 += network_layer_0.T.dot(layer_1_gradient)
    #3,4                              #4,3                 #4,4
    

Error: 0.531632051031
Error: 0.00505037626601
Error: 0.00348840629507
Error: 0.00281485397125
Error: 0.00241907662083
Error: 0.00215157617252
Error: 0.00195552338178
Error: 0.00180400823738
Error: 0.00168243910775
Error: 0.00158213391759


In [51]:
synaptic_weight_for_layer_0 = 2*np.random.random((3, 4)) - 1
synaptic_weight_for_layer_1 = 2*np.random.random((4, 4)) - 1
synaptic_weight_for_layer_2 = 2*np.random.random((4, 1)) - 1
#Real Training!
for j in range(100000):
    
    #Forward Propagation through the network layers 0, 1, & 2
    network_layer_0 = input_data
            # 4, 3
    network_layer_1 = activate(np.dot(network_layer_0, synaptic_weight_for_layer_0))
            #4,4           #             4,3              3, 4   
    network_layer_2 = activate(np.dot(network_layer_1, synaptic_weight_for_layer_1))
            #4, 4            #              4, 4             5, 4  
    network_layer_3 = activate(np.dot(network_layer_2, synaptic_weight_for_layer_2))
             #4, 1          #               4 ,  4             4, 1
    
    network_layer_3_error = output_labels - network_layer_3
    
    layer_3_gradient = network_layer_3_error * activate(network_layer_3, deriv=True)
    
    #calculate the error for network_layer_2
    network_layer_2_error = layer_3_gradient.dot(synaptic_weight_for_layer_2.T)
    
    if j % 10000 == 0:
        print("Error: " + str(np.mean(np.abs(network_layer_3_error))))
        
    #Use the network_layer_2_error to compute the gradient to start backpropagation
    layer_2_gradient = network_layer_2_error * activate(network_layer_2, deriv=True)
    
    #calculate the error for network_layer_1
    network_layer_1_error = layer_2_gradient.dot(synaptic_weight_for_layer_1.T)
    
    #Use the network_layer_1_error to compute the gradient for network_layer_1
    layer_1_gradient = network_layer_1_error * activate(network_layer_1, deriv=True)
    
    #Update the synaptic weights using the gradients
    synaptic_weight_for_layer_2 += network_layer_2.T.dot(layer_3_gradient)
    synaptic_weight_for_layer_1 += network_layer_1.T.dot(layer_2_gradient)
    synaptic_weight_for_layer_0 += network_layer_0.T.dot(layer_1_gradient)
    
    

Error: 0.50308912846
Error: 0.00460415404965
Error: 0.00317985865615
Error: 0.00256693045279
Error: 0.0022068654229
Error: 0.00196347469691
Error: 0.00178505381013
Error: 0.00164713202629
Error: 0.00153644312365
Error: 0.00144509411104


In [41]:
# Real testing!
print(np.dot(np.array([0, 0, 1]), synaptic_weight_for_layer_0))

[-2.58362455 -1.48740034 -1.99122825  1.44716657 -2.19739673]


In [28]:
# Real testing!
input_data2 = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
output = activate(np.dot(input_data2, synaptic_weights))
output

array([[ 0.00679732],
       [ 0.99445537],
       [ 0.99548489],
       [ 0.0055365 ]])

In [39]:
# Real testing!
network_layer_0 = input_data
network_layer_1 = activate(np.dot(network_layer_0, synaptic_weight_for_layer_0))
network_layer_2 = activate(np.dot(network_layer_1, synaptic_weight_for_layer_1))

In [45]:
network_layer_2

array([[  6.12078124e-04],
       [  9.99378126e-01],
       [  9.99463151e-01],
       [  4.70690577e-04]])