In [1]:
import numpy as np #linear algebra

In [2]:
#Input Data
input_data = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
output_labels = np.array([[0, 1, 1, 0]]).T

In [3]:
print(input_data)
print(output_labels)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [4]:
def activate(x, deriv=False):
    if (deriv==True):
        return(x*(1-x))
    return 1/(1+np.exp(-x))

In [7]:
#weight matrix
synaptic_weights = 2 * np.random.random((3, 1)) - 1

print(synaptic_weights)

[[-0.61409162]
 [-0.74875194]
 [ 0.4062854 ]]


In [8]:
output = activate(np.dot(input_data, synaptic_weights))

##This is our first guess
output

array([[0.60019685],
       [0.27756784],
       [0.4482346 ],
       [0.41521045]])

In [9]:
error = output_labels - output

In [10]:
#example of iteration of training
for iteration in range(10000):
    output = activate(np.dot(input_data, synaptic_weights))
    error = output_labels - output
    synaptic_weights += np.dot(input_data.T, error * activate(output, True))

In [11]:
#testing example
print(activate(np.dot(np.array([1, 0, 0]), synaptic_weights)))
#Will be approximetly 1 which is close to the 1st element

[0.99993702]


In [12]:
#2 weight values, 1 for each output layer that is used as an input layer in the neural network
synaptic_weight_for_layer_0 = 2*np.random.random((3, 4)) - 1
synaptic_weight_for_layer_1 = 2*np.random.random((4, 1)) - 1

In [13]:
print(synaptic_weight_for_layer_0)
print(synaptic_weight_for_layer_1)

[[ 0.81778825  0.85486314  0.56671767  0.66395905]
 [-0.21155296 -0.37610242  0.82961784  0.47900327]
 [-0.13754931  0.37418027 -0.08007347 -0.96701611]]
[[-0.12492157]
 [ 0.67251512]
 [ 0.16502545]
 [ 0.30946658]]


In [14]:
#Real Training!
for j in range(100000):
    
    #Forward Propagation through the network layers 0, 1, & 2
    network_layer_0 = input_data
    # 4, 3
    network_layer_1 = activate(np.dot(network_layer_0, synaptic_weight_for_layer_0))
    #4, 4                                #4,3               #3,4
    network_layer_2 = activate(np.dot(network_layer_1, synaptic_weight_for_layer_1))
    #4,1                                 #4,4               #4,1
    
    #calculate the error for network_layer_2
    network_layer_2_error = output_labels - network_layer_2
    #4,1                        #4,1            #4,1
    
    if j % 10000 == 0:
        print("Error: " + str(np.mean(np.abs(network_layer_2_error))))
        
    #Use the network_layer_2_error to compute the gradient to start backpropagation
    layer_2_gradient = network_layer_2_error * activate(network_layer_2, deriv=True)
    #4,1                    #4,1                  #4,1
    
    #calculate the error for network_layer_1
    network_layer_1_error = layer_2_gradient.dot(synaptic_weight_for_layer_1.T)
    #4,4                      #4,1                  #1,4
    
    #Use the network_layer_1_error to compute the gradient for network_layer_1
    layer_1_gradient = network_layer_1_error * activate(network_layer_1, deriv=True)
    #4,4                  #4,4                      #4,4
    
    #Update the synaptic weights using the gradients
    synaptic_weight_for_layer_1 += network_layer_1.T.dot(layer_2_gradient)
    #4,1                              #4,4                 #4,1
    synaptic_weight_for_layer_0 += network_layer_0.T.dot(layer_1_gradient)
    #3,4                              #4,3                 #4,4
    

Error: 0.48022968732074905
Error: 0.004427173721817367
Error: 0.00305063787137495
Error: 0.0024588096356032924
Error: 0.0021115890101118884
Error: 0.0018771456470123597
Error: 0.0017054484575699863
Error: 0.0015728329951799334
Error: 0.0014664782852052776
Error: 0.0013787609028372413


In [15]:
synaptic_weight_for_layer_0 = 2*np.random.random((3, 4)) - 1
synaptic_weight_for_layer_1 = 2*np.random.random((4, 4)) - 1
synaptic_weight_for_layer_2 = 2*np.random.random((4, 1)) - 1
#Real Training!
for j in range(100000):
    
    #Forward Propagation through the network layers 0, 1, & 2
    network_layer_0 = input_data
            # 4, 3
    network_layer_1 = activate(np.dot(network_layer_0, synaptic_weight_for_layer_0))
            #4,4           #             4,3              3, 4   
    network_layer_2 = activate(np.dot(network_layer_1, synaptic_weight_for_layer_1))
            #4, 4            #              4, 4             5, 4  
    network_layer_3 = activate(np.dot(network_layer_2, synaptic_weight_for_layer_2))
             #4, 1          #               4 ,  4             4, 1
    
    network_layer_3_error = output_labels - network_layer_3
    
    layer_3_gradient = network_layer_3_error * activate(network_layer_3, deriv=True)
    
    #calculate the error for network_layer_2
    network_layer_2_error = layer_3_gradient.dot(synaptic_weight_for_layer_2.T)
    
    if j % 10000 == 0:
        print("Error: " + str(np.mean(np.abs(network_layer_3_error))))
        
    #Use the network_layer_2_error to compute the gradient to start backpropagation
    layer_2_gradient = network_layer_2_error * activate(network_layer_2, deriv=True)
    
    #calculate the error for network_layer_1
    network_layer_1_error = layer_2_gradient.dot(synaptic_weight_for_layer_1.T)
    
    #Use the network_layer_1_error to compute the gradient for network_layer_1
    layer_1_gradient = network_layer_1_error * activate(network_layer_1, deriv=True)
    
    #Update the synaptic weights using the gradients
    synaptic_weight_for_layer_2 += network_layer_2.T.dot(layer_3_gradient)
    synaptic_weight_for_layer_1 += network_layer_1.T.dot(layer_2_gradient)
    synaptic_weight_for_layer_0 += network_layer_0.T.dot(layer_1_gradient)
    
    

Error: 0.5022857762732069
Error: 0.0043978172554067566
Error: 0.0030506199489646825
Error: 0.002468090359593145
Error: 0.0021250777888578033
Error: 0.001892859799345653
Error: 0.0017224385522338075
Error: 0.0015905845699478883
Error: 0.0014846887298173512
Error: 0.001397241618282188


In [16]:
# Real testing!
print(np.dot(np.array([0, 0, 1]), synaptic_weight_for_layer_0))

[ 0.91002613  1.64719341 -1.098692   -1.83607419]


In [17]:
# Real testing!
input_data2 = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
output = activate(np.dot(input_data2, synaptic_weights))
output

array([[0.009672  ],
       [0.992115  ],
       [0.99359181],
       [0.00786314]])

In [18]:
# Real testing!
network_layer_0 = input_data
network_layer_1 = activate(np.dot(network_layer_0, synaptic_weight_for_layer_0))
network_layer_2 = activate(np.dot(network_layer_1, synaptic_weight_for_layer_1))

In [19]:
network_layer_2

array([[0.07249043, 0.96175782, 0.1723786 , 0.14259664],
       [0.91621729, 0.04535798, 0.77719936, 0.79594133],
       [0.92248722, 0.03798777, 0.7796018 , 0.80508792],
       [0.06662148, 0.96833101, 0.16985724, 0.1353103 ]])